# Generated by Django 4.2.2 on 2024-08-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
